name: Build ffmpeg

on:
  workflow_dispatch:

jobs:
  build_ffmpeg:
    name: Build ffmpeg
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [win32,win64] #win32 , win64 or multi
        variant: [gpl,lgpl,gpl-shared,lgpl-shared]
        version: [none,n4.3.1]
    steps:
      - name: Preparing build
        run: |
          git clone https://github.com/rdp/ffmpeg-windows-build-helpers.git
          cd ffmpeg-windows-build-helpers
          sudo apt-get update
          sudo apt-get install subversion ragel curl texinfo g++ bison flex cvs yasm automake libtool autoconf gcc cmake git make pkg-config zlib1g-dev mercurial unzip pax nasm gperf autogen bzip2 autoconf-archive p7zip-full clang python3 python3-pip python3-setuptools python3-wheel python3-distutils python-is-python3 ninja-build -y
          sudo pip3 install meson ninja
      - name: Build ffmpeg
        run: |
          if [[ ${{ matrix.variant }} == *"lgpl"* ]];then GPL="n";else GPL="y";fi
          if [[ ${{ matrix.variant }} == *"shared"* ]];then SHARED="y";else SHARED="n";fi
          if [[ ${{ matrix.version }} == *"none"* ]];then VERSION="";else VERSION="--ffmpeg-git-checkout-version=${{ matrix.version }}";fi
          cd ffmpeg-windows-build-helpers
          ./cross_compile_ffmpeg.sh --build-ffmpeg-shared=$SHARED $VERSION --enable-gpl=$GPL --compiler-flavors=${{ matrix.target }} --build-intel-qsv=y --build-amd-amf=y
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ffmpeg_build
          path: ffmpeg-windows-build-helpers/sandbox/win*/ffmpeg*